name: Rust tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust ${{ matrix.toolchain }}
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        if: matrix.toolchain != 'stable'
        run: cargo test --all-targets --all-features --workspace --verbose

      - name: Install cargo-llvm-cov
        if: matrix.toolchain == 'stable'
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests & Generate code coverage
        if: matrix.toolchain == 'stable'
        run: cargo llvm-cov --all-targets --all-features --workspace --codecov --output-path codecov.json -vv
      - name: Upload coverage artifact
        if: matrix.toolchain == 'stable'
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: coverage
          path: codecov.json
          retention-days: 7

      - name: Run doc-tests
        run: cargo test --doc --verbose


  upload-coverage:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
