name: Rust tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    strategy:
      matrix:
        include:
        - toolchain: stable
        - toolchain: beta
        - toolchain: nightly

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust ${{ matrix.toolchain }}
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      if: matrix.toolchain != 'stable'
      run: cargo test --verbose

    - name: Install cargo-llvm-cov
      if: matrix.toolchain == 'stable'
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Run tests & Generate code coverage
      if: matrix.toolchain == 'stable'
      run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
    - name: Upload coverage artifact
      if: matrix.toolchain == 'stable'
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: coverage
        path: codecov.json
        retention-days: 7


  upload_coverage:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download coverage artifact
      uses: actions/download-artifact@v3
      with:
        name: coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: codecov.json
        fail_ci_if_error: true
