name: Check TCK

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: tck
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BADGE_GIST_ID: e795d8d23466d049a08e03c23301e996

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - name: Checkout https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-tck
      run: git clone --depth=1 https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-tck.git asciidoc-tck
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      working-directory: asciidoc-tck
      run: |
        npm ci
        {
          echo 'import {inspect} from "node:util";'
          echo 'inspect.defaultOptions.depth = null;'
          echo 'Error.stackTraceLimit = 0;'
        } >> depth.js
    - name: Run AsciiDoc TCK
      continue-on-error: true
      id: tck
      working-directory: asciidoc-tck
      env:
        NODE_OPTIONS: --import ./depth.js
      run: |
        npx asciidoc-tck cli -c ${GITHUB_WORKSPACE}/target/debug/asciidoc2rs | tee output.txt
        grep 'ℹ' output.txt | awk '{print $2"="$3}' >> $GITHUB_OUTPUT
        sed -i'' '/^ℹ/d' output.txt

    - name: Generate summary
      continue-on-error: true
      working-directory: asciidoc-tck
      run: |
        {
          echo '## TCK result'
          echo ''
          sed -E 's/▶/-/;s/✔/- [x]/;s/✖/- [ ]/' output.txt
          echo ''
        } >> $GITHUB_STEP_SUMMARY

    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistId: ${{ env.BADGE_GIST_ID }}
        filename: asciidoc2rs-passed.json
        label: TCK passed
        color: success
        message: ${{ steps.tck.outputs.pass }}
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistId: ${{ env.BADGE_GIST_ID }}
        filename: asciidoc2rs-failed.json
        label: TCK failed
        color: important
        message: ${{ steps.tck.outputs.fail }}
